import { Mood, Playlist, Track, ChatMessage, HistoryItem, UserProfile } from './types';

export const MOODS: Mood[] = [
  {
    id: 'happy',
    name: 'Happy',
    emoji: '☀️',
    description: 'Upbeat, golden, energetic pop & warm melodies',
    color: 'from-amber-400 via-orange-500 to-yellow-500',
    bgGlow: 'rgba(245, 158, 11, 0.25)',
    tagline: 'High serotonin grooves & sunshine rhythms',
    energyLevel: 88,
    valenceLevel: 95,
  },
  {
    id: 'sad',
    name: 'Sad',
    emoji: '🌧️',
    description: 'Melancholic acoustic, quiet piano & deep soothing vocals',
    color: 'from-blue-500 via-indigo-600 to-slate-700',
    bgGlow: 'rgba(99, 102, 241, 0.25)',
    tagline: 'Gentle melodies for reflective & rainy moments',
    energyLevel: 25,
    valenceLevel: 20,
  },
  {
    id: 'relaxed',
    name: 'Relaxed',
    emoji: '🌿',
    description: 'Chill ambient, lofi beats & smooth jazzy soundscapes',
    color: 'from-emerald-400 via-teal-500 to-cyan-600',
    bgGlow: 'rgba(20, 184, 166, 0.25)',
    tagline: 'Unwind with slow tempos & tranquil atmosphere',
    energyLevel: 35,
    valenceLevel: 75,
  },
  {
    id: 'excited',
    name: 'Excited',
    emoji: '⚡',
    description: 'High-octane EDM, synthwave & driving dance anthems',
    color: 'from-fuchsia-500 via-purple-600 to-pink-500',
    bgGlow: 'rgba(217, 70, 239, 0.3)',
    tagline: 'Adrenaline boosters & festival mainstage vibes',
    energyLevel: 98,
    valenceLevel: 90,
  },
  {
    id: 'stressed',
    name: 'Stressed',
    emoji: '🧘',
    description: 'Deep calm sound baths, 432Hz ambient & slow piano strings',
    color: 'from-purple-500 via-violet-600 to-indigo-800',
    bgGlow: 'rgba(168, 85, 247, 0.3)',
    tagline: 'Lower heart rate & ease tension with soft acoustics',
    energyLevel: 15,
    valenceLevel: 60,
  },
  {
    id: 'focused',
    name: 'Focused',
    emoji: '🎧',
    description: 'Instrumental flow state, cyberpunk synth & lofi study lounge',
    color: 'from-cyan-400 via-blue-600 to-violet-600',
    bgGlow: 'rgba(6, 182, 212, 0.25)',
    tagline: 'Binaural flow & deep work instrumental precision',
    energyLevel: 60,
    valenceLevel: 70,
  },
  {
    id: 'nostalgic',
    name: 'Nostalgic',
    emoji: '📼',
    description: '80s synth-pop, classic 90s indie & timeless retro warmth',
    color: 'from-rose-400 via-pink-600 to-purple-600',
    bgGlow: 'rgba(244, 63, 94, 0.25)',
    tagline: 'Bittersweet memories & vintage golden age tracks',
    energyLevel: 65,
    valenceLevel: 68,
  },
];

export const MOCK_TRACKS: Track[] = [
  {
    id: 't1',
    title: 'Neon Horizons',
    artist: 'Celestial Echoes',
    album: 'Midnight Pulse',
    duration: '3:45',
    durationSeconds: 225,
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&q=80',
    mood: 'excited',
    liked: true,
    genre: 'Synthwave',
    year: '2025',
    bpm: 124,
  },
  {
    id: 't2',
    title: 'Velvet Rain',
    artist: 'Luna Solis',
    album: 'Soft Reverie',
    duration: '4:12',
    durationSeconds: 252,
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&q=80',
    mood: 'relaxed',
    liked: true,
    genre: 'Lo-Fi Chill',
    year: '2024',
    bpm: 82,
  },
  {
    id: 't3',
    title: 'Midnight Sun',
    artist: 'Kairo & The Wave',
    album: 'Euphoria',
    duration: '3:18',
    durationSeconds: 198,
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&q=80',
    mood: 'happy',
    liked: false,
    genre: 'Indie Pop',
    year: '2025',
    bpm: 118,
  },
  {
    id: 't4',
    title: 'Quantum Drift',
    artist: 'Neural Odyssey',
    album: 'Deep Focus Vol. 3',
    duration: '5:04',
    durationSeconds: 304,
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&q=80',
    mood: 'focused',
    liked: true,
    genre: 'Ambient Electronics',
    year: '2024',
    bpm: 100,
  },
  {
    id: 't5',
    title: 'Tears in November',
    artist: 'Oliver Grey',
    album: 'Whispers in Autumn',
    duration: '4:35',
    durationSeconds: 275,
    coverUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=300&q=80',
    mood: 'sad',
    liked: false,
    genre: 'Acoustic Folk',
    year: '2023',
    bpm: 72,
  },
  {
    id: 't6',
    title: 'Sanctuary 432Hz',
    artist: 'Aura Soundscapes',
    album: 'Stress Dissolve',
    duration: '6:10',
    durationSeconds: 370,
    coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=300&q=80',
    mood: 'stressed',
    liked: true,
    genre: 'Meditation',
    year: '2025',
    bpm: 60,
  },
  {
    id: 't7',
    title: 'Cassette Dreams',
    artist: 'Retro Static',
    album: '1984 Flashback',
    duration: '3:50',
    durationSeconds: 230,
    coverUrl: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=300&q=80',
    mood: 'nostalgic',
    liked: true,
    genre: 'Retro Pop',
    year: '2024',
    bpm: 110,
  },
  {
    id: 't8',
    title: 'Solar Flare',
    artist: 'HyperDrive',
    album: 'Overdrive 2099',
    duration: '3:28',
    durationSeconds: 208,
    coverUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&q=80',
    mood: 'excited',
    liked: false,
    genre: 'Future Bass',
    year: '2025',
    bpm: 140,
  },
  {
    id: 't9',
    title: 'Coffee Shop Serenade',
    artist: 'Maya Lin',
    album: 'Sunday Morning Coffee',
    duration: '3:15',
    durationSeconds: 195,
    coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=300&q=80',
    mood: 'relaxed',
    liked: true,
    genre: 'Jazz Hop',
    year: '2024',
    bpm: 85,
  },
  {
    id: 't10',
    title: 'Golden Hour Smile',
    artist: 'The Brightside',
    album: 'Clear Skies',
    duration: '3:02',
    durationSeconds: 182,
    coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=300&q=80',
    mood: 'happy',
    liked: true,
    genre: 'Indie Dance',
    year: '2025',
    bpm: 122,
  },
];

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: 'pl-excited-1',
    title: 'Cybernetic Energy Boost',
    description: 'High-BPM synthwave and euphoric EDM curated to elevate your heart rate and pump motivation.',
    mood: 'excited',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80',
    trackCount: 12,
    totalDuration: '48 min',
    aiExplanation: 'MoodMuse AI detected high energy markers and elevated valence. We selected tracks with 120+ BPM, sharp snare patterns, and resonant synth leads to fuel your excitement without cognitive fatigue.',
    curator: 'MoodMuse AI SynthEngine',
    likesCount: 3420,
    tags: ['Synthwave', 'EDM', 'Peak Energy', 'High Tempo'],
    isSaved: true,
    createdDate: '2 hours ago',
    tracks: [
      MOCK_TRACKS[0], // Neon Horizons
      MOCK_TRACKS[7], // Solar Flare
      {
        id: 't11',
        title: 'Hyperlight Speed',
        artist: 'Pulse Architect',
        album: 'Neo Tokyo',
        duration: '4:01',
        durationSeconds: 241,
        coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&q=80',
        mood: 'excited',
        genre: 'Electro',
      },
      {
        id: 't12',
        title: 'Overdrive Protocol',
        artist: 'Vapor Wave',
        album: 'Cybernetic Horizon',
        duration: '3:40',
        durationSeconds: 220,
        coverUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=300&q=80',
        mood: 'excited',
        genre: 'Synthwave',
      },
      {
        id: 't13',
        title: 'Starlight Symphony',
        artist: 'Astro Beats',
        album: 'Galaxy Glow',
        duration: '3:55',
        durationSeconds: 235,
        coverUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&q=80',
        mood: 'excited',
        genre: 'Dance',
      },
    ],
  },
  {
    id: 'pl-relaxed-1',
    title: 'Rainy Cafe & Lofi Sanctuary',
    description: 'Soft vinyl crackles, warm Fender Rhodes chords, and soothing lofi hip-hop for instant relaxation.',
    mood: 'relaxed',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&q=80',
    trackCount: 16,
    totalDuration: '52 min',
    aiExplanation: 'Selected based on your calm evening prompt. Soft organic drum textures and micro-reverb acoustics trigger theta wave relaxation patterns to lower stress levels.',
    curator: 'MoodMuse AI ChillLab',
    likesCount: 8910,
    tags: ['Lo-Fi', 'Chillhop', 'Vinyl', 'Relaxing'],
    isSaved: true,
    createdDate: 'Yesterday',
    tracks: [
      MOCK_TRACKS[1], // Velvet Rain
      MOCK_TRACKS[8], // Coffee Shop Serenade
      {
        id: 't14',
        title: 'Late Night Study',
        artist: 'Nostalgia Lofi',
        album: 'Midnight Tea',
        duration: '2:45',
        durationSeconds: 165,
        coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=300&q=80',
        mood: 'relaxed',
        genre: 'Lo-Fi',
      },
      {
        id: 't15',
        title: 'Window Sill Drops',
        artist: 'Sleepy Panda',
        album: 'Cozy Dreams',
        duration: '3:08',
        durationSeconds: 188,
        coverUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=300&q=80',
        mood: 'relaxed',
        genre: 'Ambient',
      },
    ],
  },
  {
    id: 'pl-happy-1',
    title: 'Serotonin Sunshine Pop',
    description: 'Radiant indie dance, bouncy basslines, and golden hour harmonies guaranteed to spark joy.',
    mood: 'happy',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80',
    trackCount: 14,
    totalDuration: '45 min',
    aiExplanation: 'Generated for uplifting morning routines. Features major key progressions, organic clapping samples, and catchy hooks designed to stimulate dopamine release.',
    curator: 'MoodMuse AI Euphoria',
    likesCount: 5210,
    tags: ['Upbeat', 'Indie Pop', 'Summer Vibes', 'Feel Good'],
    isSaved: false,
    createdDate: '3 days ago',
    tracks: [
      MOCK_TRACKS[2], // Midnight Sun
      MOCK_TRACKS[9], // Golden Hour Smile
      {
        id: 't16',
        title: 'Beachside Funk',
        artist: 'The Groovers',
        album: 'Tropic Sunrise',
        duration: '3:34',
        durationSeconds: 214,
        coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=300&q=80',
        mood: 'happy',
        genre: 'Funk Pop',
      },
    ],
  },
  {
    id: 'pl-focused-1',
    title: 'Deep Work Flow State 100Hz',
    description: 'Binaural ambient pads and steady minimalist synth pulses to sustain hyper-focus and coding productivity.',
    mood: 'focused',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&q=80',
    trackCount: 10,
    totalDuration: '64 min',
    aiExplanation: 'Curated specifically without lyric distractions. Uses steady sub-bass frequencies and predictable rhythmic arpeggios that help enter alpha wave focus states.',
    curator: 'MoodMuse AI FocusGrid',
    likesCount: 12400,
    tags: ['Instrumental', 'Deep Work', 'Binaural', 'Coding'],
    isSaved: true,
    createdDate: '4 days ago',
    tracks: [
      MOCK_TRACKS[3], // Quantum Drift
      {
        id: 't17',
        title: 'Cognitive Matrix',
        artist: 'Mindwave',
        album: 'Alpha States',
        duration: '6:15',
        durationSeconds: 375,
        coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=300&q=80',
        mood: 'focused',
        genre: 'Ambient',
      },
    ],
  },
  {
    id: 'pl-stressed-1',
    title: 'Anxiety Dissolve & Decompress',
    description: '432Hz tuned sound bowls, serene string quartets, and meditative ambient soundscapes.',
    mood: 'stressed',
    coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
    trackCount: 8,
    totalDuration: '42 min',
    aiExplanation: 'Targeted decompression for high cognitive load or stress. Features long sustained drones and slow tempo (under 65 BPM) to sync heart rhythms down to a relaxed resting state.',
    curator: 'MoodMuse AI Wellness',
    likesCount: 6180,
    tags: ['432Hz', 'Sound Bath', 'Calm', 'Mindfulness'],
    isSaved: false,
    createdDate: '5 days ago',
    tracks: [
      MOCK_TRACKS[5], // Sanctuary 432Hz
    ],
  },
  {
    id: 'pl-nostalgic-1',
    title: '1988 Neon Highway',
    description: 'Retro analog synths, VHS cassette aesthetics, and timeless melancholic 80s nostalgia.',
    mood: 'nostalgic',
    coverUrl: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&q=80',
    trackCount: 15,
    totalDuration: '58 min',
    aiExplanation: 'Blends classic tape saturation, chorus pedals, and vintage drum machines to evoke bittersweet golden era memories.',
    curator: 'MoodMuse AI RetroVault',
    likesCount: 4120,
    tags: ['80s', 'Retro', 'Synthwave', 'Analog'],
    isSaved: true,
    createdDate: '1 week ago',
    tracks: [
      MOCK_TRACKS[6], // Cassette Dreams
    ],
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'm1',
    sender: 'ai',
    text: "Welcome back! I'm MoodMuse AI, your emotional sonic companion. How are you feeling right now, or what kind of atmosphere are you trying to build?",
    timestamp: '10:00 AM',
    suggestedPrompts: [
      "I'm feeling energetic and want music for a high-tempo gym workout!",
      "I have a tight deadline and need music for deep focus coding.",
      "Feeling a bit overwhelmed and need soothing acoustic rain sounds.",
      "Give me 80s retro nostalgic synthwave for a night drive.",
    ],
  },
  {
    id: 'm2',
    sender: 'user',
    text: "I've been grinding code for 4 hours and my mind feels tired, but I still have a project to finish. Need something focused yet uplifting!",
    timestamp: '10:02 AM',
  },
  {
    id: 'm3',
    sender: 'ai',
    text: "I detect a mix of **Mental Fatigue** with a desire for **Focused Flow State**. I've assembled a custom playlist featuring subtle sub-bass pulses, 110 BPM melodic synth grooves, and zero disruptive vocals to keep your brain engaged without overload.",
    timestamp: '10:03 AM',
    detectedMood: 'focused',
    recommendedPlaylist: MOCK_PLAYLISTS[3],
    suggestedPrompts: [
      "Add more lofi acoustic tracks to this list",
      "Switch to high-energy electronic beats instead",
      "Explain why these frequencies help focus",
    ],
  },
];

export const MOCK_HISTORY: HistoryItem[] = [
  {
    id: 'h1',
    date: 'Today',
    time: '09:45 AM',
    mood: 'focused',
    userPrompt: 'Need music for late night TypeScript debugging session',
    playlistRecommended: MOCK_PLAYLISTS[3],
    tracksListened: 14,
    sessionDuration: '1h 22m',
  },
  {
    id: 'h2',
    date: 'Yesterday',
    time: '06:15 PM',
    mood: 'excited',
    userPrompt: 'Pre-workout pump playlist with intense bass drop',
    playlistRecommended: MOCK_PLAYLISTS[0],
    tracksListened: 9,
    sessionDuration: '45m',
  },
  {
    id: 'h3',
    date: 'Aug 4, 2026',
    time: '08:30 PM',
    mood: 'relaxed',
    userPrompt: 'Unwinding after long meeting filled workday',
    playlistRecommended: MOCK_PLAYLISTS[1],
    tracksListened: 18,
    sessionDuration: '1h 05m',
  },
  {
    id: 'h4',
    date: 'Aug 3, 2026',
    time: '02:10 PM',
    mood: 'happy',
    userPrompt: 'Sunny Sunday drive along coastal highway',
    playlistRecommended: MOCK_PLAYLISTS[2],
    tracksListened: 12,
    sessionDuration: '48m',
  },
  {
    id: 'h5',
    date: 'Aug 1, 2026',
    time: '11:00 PM',
    mood: 'stressed',
    userPrompt: 'Can not sleep, mind racing with thoughts',
    playlistRecommended: MOCK_PLAYLISTS[4],
    tracksListened: 6,
    sessionDuration: '35m',
  },
];

export const MOCK_USER_PROFILE: UserProfile = {
  name: 'Alex Vance',
  username: '@alexvance_vibes',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80',
  bio: 'Audio enthusiast, software engineer, and late-night synthwave seeker.',
  memberSince: 'March 2025',
  listenerLevel: 'Master Mood Alchemist',
  preferredLanguage: 'English & Instrumentals',
  favoriteGenres: [
    { id: 'g1', name: 'Synthwave & Electronic', percentage: 38, color: 'from-purple-500 to-indigo-600' },
    { id: 'g2', name: 'Lo-Fi Chill & Jazz Hop', percentage: 26, color: 'from-teal-400 to-emerald-600' },
    { id: 'g3', name: 'Indie Pop & Alternative', percentage: 20, color: 'from-amber-400 to-pink-500' },
    { id: 'g4', name: 'Ambient & Binaural', percentage: 16, color: 'from-cyan-400 to-blue-600' },
  ],
  favoriteArtists: [
    {
      id: 'a1',
      name: 'Celestial Echoes',
      imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&q=80',
      genre: 'Synthwave',
      followers: '1.2M',
      topTrack: 'Neon Horizons',
    },
    {
      id: 'a2',
      name: 'Luna Solis',
      imageUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&q=80',
      genre: 'Lo-Fi Chill',
      followers: '850K',
      topTrack: 'Velvet Rain',
    },
    {
      id: 'a3',
      name: 'Kairo & The Wave',
      imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&q=80',
      genre: 'Indie Pop',
      followers: '2.4M',
      topTrack: 'Midnight Sun',
    },
  ],
  stats: {
    playlistsGenerated: 84,
    hoursListened: 142,
    moodStreakDays: 19,
    topMoodThisWeek: 'focused',
  },
};
